# Generated by Django 5.2.1 on 2025-05-29 01:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0003_rename_userprofile_profile"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="address",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="annual_leave",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name="profile",
            name="gross_pay",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name="profile",
            name="hours_worked",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="profile",
            name="job_title",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="profile",
            name="net_pay",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name="profile",
            name="pay_rate",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="profile",
            name="payment_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="super_contribution",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name="profile",
            name="tax",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.CreateModel(
            name="Payslip",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("job_title", models.CharField(max_length=100)),
                ("address", models.TextField()),
                ("period_start", models.DateField()),
                ("period_end", models.DateField()),
                ("payment_date", models.DateField()),
                ("gross_earning", models.DecimalField(decimal_places=2, max_digits=10)),
                ("net_pay", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "superannuation",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("employee_type", models.CharField(max_length=50)),
                ("units", models.DecimalField(decimal_places=2, max_digits=5)),
                ("rate", models.DecimalField(decimal_places=2, max_digits=10)),
                ("tax", models.DecimalField(decimal_places=2, max_digits=10)),
                ("leave_accrued", models.DecimalField(decimal_places=3, max_digits=5)),
                ("leave_taken", models.DecimalField(decimal_places=3, max_digits=5)),
                ("payment_mode", models.CharField(default="Cash", max_length=50)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
