# Generated by Django 5.2.1 on 2025-05-29 23:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0004_profile_address_profile_annual_leave_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="address",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="annual_leave",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="gross_pay",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="hours_worked",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="job_title",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="net_pay",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="pay_rate",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="payment_date",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="super_contribution",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="tax",
        ),
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                (
                    "salary_type",
                    models.CharField(
                        choices=[("hourly", "Hourly"), ("yearly", "Yearly")],
                        max_length=10,
                    ),
                ),
                ("salary_amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("role", models.CharField(max_length=100)),
                ("employee_id", models.CharField(max_length=50)),
                ("govt_id_number", models.CharField(max_length=100)),
                ("ssn_number", models.CharField(max_length=100)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("phone", models.CharField(blank=True, max_length=15, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="JobRole",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("salary_min", models.DecimalField(decimal_places=2, max_digits=10)),
                ("salary_max", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "employment_type",
                    models.CharField(
                        choices=[
                            ("full-time", "Full-time"),
                            ("part-time", "Part-time"),
                            ("contract", "Contract"),
                        ],
                        max_length=15,
                    ),
                ),
                ("location", models.CharField(max_length=100)),
                (
                    "experience_level",
                    models.CharField(
                        choices=[
                            ("entry", "Entry"),
                            ("mid", "Mid"),
                            ("senior", "Senior"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Payslip",
        ),
    ]
