# Generated by Django 5.2.1 on 2025-05-30 01:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0005_remove_profile_address_remove_profile_annual_leave_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobrole",
            name="keywords",
            field=models.TextField(
                blank=True, help_text="Comma-separated list of mandatory keywords"
            ),
        ),
    ]
