# Generated by Django 5.2.1 on 2025-05-31 01:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0006_jobrole_keywords"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="salary_type",
            field=models.CharField(choices=[("hr", "Hr"), ("yr", "Yr")], max_length=10),
        ),
        migrations.AlterField(
            model_name="jobrole",
            name="keywords",
            field=models.TextField(blank=True),
        ),
    ]
