# Generated by Django 5.2.1 on 2025-06-01 01:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0009_timesheet"),
    ]

    operations = [
        migrations.AddField(
            model_name="timesheet",
            name="rejected",
            field=models.BooleanField(default=False),
        ),
    ]
